import React from 'react'; 


export const OPEN_CART = "OPEN_CART";
export const LOAD_STORE = 'LOAD_STORE';
export const ADD_CART = 'ADD_CART';

export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

// for chat box
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const INITIALIZE_SOCKET_ROOM = 'INITIALIZE_SOCKET_ROOM';
